# ----------------------
# Netlify Build Settings
# ----------------------
[build]
  # SSR 生产构建
  command = "npm run build"
  # Astro 输出目录
  publish = "dist"

# ----------------------
# Netlify Functions 设置
# ----------------------
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ----------------------
# SSR 路由转发
# output = "server" 必须有这条 redirect
# ----------------------
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/astro"
  status = 200
